function [isAAReturnValue] = isAA (c)
% function returns true if the given character c is a valid amino acid otherwise false
% 
% example for usage:
% 
% str = 'ABCDEFGHIJ';
% for ii = 1:length(str)
%       if ~isAA(str(ii))
%           fprintf('There is a problem at pos %i of the string "%s". The character "%s" is not a valid amio acid.\n', ii, str, str(ii));
%       end
% end
%
% % B. Knapp 2011-05-04
%
isAAReturnValue = false;
if (size(c,1) == 1 && size(c,2) == 1)
    isAAReturnValue=(c == 'A') || (c == 'R') || ...
                    (c == 'N') || (c == 'D') || ...
                    (c == 'C') || (c == 'E') || ...
                    (c == 'Q') || (c == 'G') || ...
                    (c == 'H') || (c == 'I') || ...
                    (c == 'L') || (c == 'K') || ...
                    (c == 'M') || (c == 'F') || ...
                    (c == 'P') || (c == 'S') || ...
                    (c == 'T') || (c == 'W') || ...
                    (c == 'Y') || (c == 'V') ;
end
